Repository traefik/mesh, pull requests merged in 2019-12, with the labels that each got.

#379 Use initContainers to fix volume permissions
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#380 Upgrade python version to 3.7 for netlify
  docs/runtime.txt
Labels: area/documentation, area/infrastructure, bot/light-review, kind/bug/fix, status/3-needs-merge

#376 Add influxDB and statsD to metrics
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
Labels: area/metrics, kind/enhancement, status/3-needs-merge

#364 Upgrade helm to v3
  Makefile
  README.md
  docs/content/index.md
  docs/content/install.md
  docs/content/quickstart.md
  helm/chart/README.md
  helm/chart/maesh/Chart.yaml
  helm/chart/maesh/requirements.yaml
  helm/chart/maesh/templates/smi/smi-access.yaml
  helm/chart/maesh/templates/smi/smi-spec.yaml
  helm/chart/maesh/templates/smi/smi-trafficsplits.yaml
  helm/chart/maesh/values.yaml
  integration/coredns_test.go
  integration/integration_test.go
  integration/kubedns_test.go
  integration/kubernetes_test.go
  integration/resources/helm/clusterrolebinding.yaml
  integration/resources/helm/serviceaccount.yaml
  integration/resources/smi/0.crds.yaml
  integration/resources/values.yaml
  integration/smi_test.go
Labels: area/helm, kind/enhancement

#386 Fix Travis Builds
  docs/check.Dockerfile
Labels: area/infrastructure, kind/bug/fix, status/3-needs-merge

#389 Update Traefik to 2.1
  helm/chart/maesh/templates/_helpers.tpl
  integration/integration_test.go
Labels: area/traefik, kind/enhancement, status/3-needs-merge

#381 Use custom separator for service name and namespace
  helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
  integration/kubernetes_test.go
  integration/resources/whoami/0-namespace.yaml
  integration/resources/whoami/0-namespaces.yaml
  integration/resources/whoami/whoami-test.yaml
  integration/smi_test.go
  internal/controller/controller.go
  internal/k8s/client.go
Labels: area/controller, area/coredns, kind/bug/fix, status/3-needs-merge
