Repository traefik/mesh, pull requests merged in 2019-11, with the labels that each got.

#325 Create API on the controller
  cmd/configuration.go
  cmd/maesh/maesh.go
  go.mod
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  internal/controller/api.go
  internal/controller/controller.go
Labels: area/api, area/controller, kind/enhancement

#338 Add examples to doc
  docs/content/examples.md
  docs/content/install.md
  docs/content/quickstart.md
  docs/mkdocs.yml
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#340 Add PR template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#333 Create a deploy log and wire to API
  go.sum
  internal/controller/api.go
  internal/controller/api_test.go
  internal/controller/controller.go
  internal/controller/log.go
  internal/controller/log_test.go
Labels: area/api, area/controller, kind/enhancement, status/3-needs-merge

#335 Add Cluster Node Status and Configuration endpoints
  internal/controller/api.go
  internal/controller/api_test.go
  internal/controller/controller.go
Labels: area/api, area/infrastructure, kind/enhancement, status/3-needs-merge

#337 Deploy to pods in parallel
  go.mod
  go.sum
  internal/controller/controller.go
Labels: area/controller, kind/enhancement, status/3-needs-merge

#345 Add API documentation
  docs/content/api.md
  docs/mkdocs.yml
  internal/controller/api.go
Labels: area/api, area/documentation, status/3-needs-merge

#342 Create a cap for the max number of deploy log entries
  internal/controller/api.go
  internal/controller/api_test.go
  internal/controller/controller.go
  internal/controller/log.go
  internal/controller/log_test.go
Labels: area/logs, kind/enhancement, status/3-needs-merge

#352 Prepare Release v0.8.0
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#353 Add platform recommendations
  docs/content/install.md
Labels: area/documentation, area/infrastructure, kind/enhancement, status/3-needs-merge

#355 Add demo example in the quickstart guide
  docs/content/quickstart.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#356 Document Maesh and SMI
  docs/content/configuration.md
  docs/content/install.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#362 Enforce HSTS with netlify toml config
  netlify.toml
Labels: bot/light-review, kind/bug/fix, status/3-needs-merge

#359 Fix panics in SMI & Kubernetes provider
  internal/providers/kubernetes/provider.go
  internal/providers/smi/provider.go
Labels: area/configuration, kind/bug/fix, provider/kubernetes, provider/smi, status/3-needs-merge

#346 Bundle SMI CRD's with helm install
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/templates/smi/smi-access.yaml
  helm/chart/maesh/templates/smi/smi-spec.yaml
  helm/chart/maesh/templates/smi/smi-trafficsplits.yaml
  helm/chart/maesh/values.yaml
  integration/integration_test.go
  integration/resources/values.yaml
Labels: area/helm, area/smi, kind/enhancement, status/3-needs-merge

#363 Prepare Release v1.0.0
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#367 Update Doc for CRD deployment
  docs/content/install.md
Labels: area/documentation, area/smi, kind/bug/fix, status/3-needs-merge

#348 Run in single namespace
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/templates/mesh/mesh-service.yaml
  internal/controller/controller.go
  internal/controller/handler.go
  internal/k8s/client.go
  internal/k8s/ignore.go
  internal/k8s/ignore_test.go
  internal/k8s/namespace.go
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/controller, kind/enhancement, status/3-needs-merge

#371 Add datadog tracing
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
  integration/resources/values.yaml
Labels: area/tracing, kind/enhancement, status/3-needs-merge

#370 Add datadog metrics
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
Labels: area/metrics, kind/enhancement, status/2-needs-review, status/3-needs-merge

#372 Make metrics subchart more configurable
  helm/chart/maesh/Guidelines.md
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
  helm/chart/maesh/charts/metrics/templates/storage.yaml
  helm/chart/maesh/charts/metrics/values.yaml
  helm/chart/maesh/values.yaml
Labels: area/configuration, area/metrics, kind/enhancement, status/3-needs-merge

#377 Add zipkin/instana/haystack to tracing
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
Labels: area/tracing, kind/enhancement, status/3-needs-merge
