Repository traefik/mesh, pull requests merged in 2019-09, with the labels that each got.

#198 Migrate to go 1.13
  .semaphoreci/setup.sh
  Dockerfile
  integration/resources/build/Dockerfile
Labels: kind/enhancement, status/3-needs-merge

#199 Fix documentation ci - disable for now
  .travis.yml
Labels: kind/bug/fix, status/3-needs-merge

#200 Documentation Polish for public release
  docs/CNAME
  docs/content/assets/styles/extra.css
  docs/content/index.md
  docs/mkdocs.yml
  docs/scripts/netlify-run.sh
  docs/theme/main.html
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#201 Fix typos
  docs/content/configuration.md
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#204 Host main documentation on gh-pages, mixed with Helm Chart
  .gitignore
  .travis.yml
  Makefile
Labels: area/documentation, area/helm, kind/enhancement, status/3-needs-merge

#205 Update documentation tooling
  docs/check.Dockerfile
  docs/docs.Dockerfile
  docs/requirements.txt
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#211 Rename some legacy links
  helm/chart/maesh/charts/metrics/Chart.yaml
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
Labels: area/helm, kind/bug/fix, status/3-needs-merge

#214 Fix CNAME for documentation
  Makefile
  docs/scripts/netlify-run.sh
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#210 Add support of coredns 1.5 and 1.6
  .semaphoreci/setup.sh
  integration/coredns_test.go
  integration/integration_test.go
  integration/kubernetes_test.go
  integration/resources/compose/k3s.yaml
  integration/resources/coredns/coredns.yaml
  integration/smi_test.go
  internal/k8s/client.go
Labels: kind/enhancement, status/3-needs-merge

#215 Fix helm chart metrics version
  .semaphoreci/job1.sh
  Makefile
  helm/chart/maesh/charts/metrics/Chart.yaml
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
  helm/chart/maesh/requirements.yaml
Labels: area/helm, kind/bug/fix, status/3-needs-merge

#222 Add few links & badges to README
  README.md
Labels: area/documentation, kind/enhancement

#223 Fixing my mistakes
  README.md
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#228 Upgrade to golanci-lint v1.18.0
  .golangci.toml
  Dockerfile
  Makefile
  cmd/configuration.go
  integration/try/try.go
  internal/controller/controller.go
  internal/controller/handler.go
  internal/deployer/deployer.go
  internal/k8s/client.go
  internal/k8s/client_mock.go
  internal/k8s/constants.go
  internal/message/message.go
  internal/providers/smi/provider.go
Labels: area/infrastructure, kind/bug/fix, status/3-needs-merge

#227 Fix helm version
  helm/chart/maesh/Chart.yaml
Labels: area/helm, kind/bug/fix, status/3-needs-merge

#229 Prepare release v0.2.1
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#230 add static configuration option for ignore namespaces
  cmd/configuration.go
  cmd/maesh/maesh.go
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/values.yaml
  internal/controller/controller.go
  internal/k8s/ignore.go
  internal/k8s/ignore_test.go
  internal/providers/smi/provider_test.go
Labels: area/configuration, kind/enhancement, status/3-needs-merge

#231 fix: maesh daemonset is not scraped by prometheus
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#232 Prepare release v0.3.0
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#226 Added nodeselector, tolerations and affinity to deployments and daemonsets
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#233 Add note about tiller RBAC on the quickstart guide
  docs/content/quickstart.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#235 Improve metrics and tracing chart
  helm/chart/maesh/charts/metrics/Chart.yaml
  helm/chart/maesh/charts/tracing/Chart.yaml
  helm/chart/maesh/requirements.yaml
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
  integration/resources/values.yaml
Labels: area/helm, area/metrics, kind/enhancement, status/3-needs-merge

#236 Migrate to traefik 2.0
  go.mod
  go.sum
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
  integration/integration_test.go
  integration/resources/values.yaml
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
Labels: kind/enhancement, status/3-needs-merge

#234 Improve grafana and prometheus liveness and readiness probes
  helm/chart/maesh/charts/metrics/Chart.yaml
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
  helm/chart/maesh/charts/tracing/Chart.yaml
  helm/chart/maesh/requirements.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#237 Prepare release v0.4.0
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#239 Use k3d to create k8s cluster instead of compose
  .semaphoreci/job2.sh
  integration/coredns_test.go
  integration/integration_test.go
  integration/kubernetes_test.go
  integration/resources/compose/k3s.yaml
  integration/smi_test.go
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#246 Add support for kubedns
  docs/content/index.md
  docs/content/install.md
  helm/chart/maesh/templates/hooks/coredns.yaml
  helm/chart/maesh/templates/hooks/prepare-hook.yaml
  helm/chart/maesh/values.yaml
  integration/coredns_test.go
  integration/integration_test.go
  integration/kubedns_test.go
  integration/kubernetes_test.go
  integration/resources/kubedns/kubedns.yaml
  integration/resources/values.yaml
  integration/smi_test.go
  internal/k8s/client.go
  internal/k8s/client_mock.go
Labels: area/helm, kind/enhancement

#247 Make Ignorenamespaces better manageable
  helm/chart/maesh/templates/_helpers.tpl
  helm/chart/maesh/templates/controller/controller-deployment.yaml
Labels: area/configuration, kind/enhancement, status/3-needs-merge
