Repository traefik/mesh, pull requests merged in 2019-10, with the labels that each got.

#256 Maesh helm install namespace aware
  helm/chart/maesh/templates/controller/controller-pdb.yaml
  helm/chart/maesh/templates/mesh/mesh-pdb.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#251 Move to stateless Kubernetes Provider
  integration/smi_test.go
  internal/controller/controller.go
  internal/k8s/client.go
  internal/k8s/client_mock.go
  internal/providers/kubernetes/fixtures/build_configuration_simple_http_middlewares.yaml
  internal/providers/kubernetes/fixtures/build_configuration_simple_tcp.yaml
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
Labels: area/configuration, kind/enhancement, provider/kubernetes, status/3-needs-merge

#262 Check the coredns pod volumes for being a configmap
  internal/k8s/client.go
Labels: area/coredns, kind/bug/fix, status/3-needs-merge

#254 Move hooks to init container and subdir
  helm/chart/maesh/templates/_helpers.tpl
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/templates/controller/controller-rbac.yaml
  helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
  helm/chart/maesh/templates/dns/coredns/coredns-deployment.yaml
  helm/chart/maesh/templates/dns/coredns/coredns-rbac.yaml
  helm/chart/maesh/templates/dns/coredns/coredns-sa.yaml
  helm/chart/maesh/templates/dns/coredns/coredns-service.yaml
  helm/chart/maesh/templates/hooks/coredns.yaml
  helm/chart/maesh/templates/hooks/prepare-hook.yaml
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/templates/mesh/mesh-sa.yaml
  helm/chart/maesh/templates/mesh/mesh-service.yaml
  integration/coredns_test.go
  integration/integration_test.go
  integration/kubernetes_test.go
  integration/smi_test.go
  integration/try/try.go
  internal/controller/controller.go
  internal/deployer/deployer.go
  internal/k8s/client.go
  internal/k8s/client_mock.go
  internal/k8s/ignore.go
  internal/providers/kubernetes/provider_test.go
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/coredns, area/helm, kind/enhancement, status/3-needs-merge

#257 image-names can be defined for all helm-charts
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
  helm/chart/maesh/charts/metrics/values.yaml
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#260 Move SMI provider to be stateless
  internal/controller/controller.go
  internal/providers/base/base.go
  internal/providers/base/base_test.go
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
  internal/providers/smi/fixtures/build_configuration_http_service.yaml
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/configuration, area/smi, kind/enhancement, status/3-needs-merge

#266 Check for Jaeger values set or take default
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
Labels: area/helm, kind/bug/fix, status/3-needs-merge

#268 Remove Configuration state from controller
  internal/controller/controller.go
  internal/deployer/deployer.go
  internal/providers/base/base.go
  internal/providers/kubernetes/provider.go
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/configuration, kind/enhancement, status/3-needs-merge

#271 Update golangci-lint to 1.20.0
  Dockerfile
  cmd/maesh/maesh.go
  cmd/prepare/prepare.go
  integration/coredns_test.go
  integration/integration_test.go
  integration/smi_test.go
  integration/try/try.go
  internal/controller/controller.go
  internal/deployer/deployer.go
  internal/k8s/client.go
  internal/k8s/client_mock.go
  internal/k8s/namespace.go
  internal/k8s/service.go
  internal/message/message.go
  internal/providers/kubernetes/provider.go
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
  internal/signals/signal.go
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#270 Remove Queues, and use channels for processing
  internal/controller/controller.go
  internal/controller/handler.go
  internal/deployer/deployer.go
  internal/message/message.go
  internal/providers/base/base.go
Labels: kind/enhancement, status/3-needs-merge

#273 Add SMI Support for TCP
  integration/resources/smi/0.crds.yaml
  integration/resources/smi/access-control/1.sas.yaml
  integration/resources/smi/access-control/2.pods.yaml
  integration/resources/smi/access-control/3.services.yaml
  integration/resources/smi/access-control/5.trs.yaml
  integration/resources/smi/access-control/6.tts.yaml
  integration/smi_test.go
  internal/controller/controller.go
  internal/k8s/client.go
  internal/k8s/client_mock.go
  internal/providers/smi/fixtures/mock_tcp.yaml
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/smi, status/2-needs-review, status/3-needs-merge

#274 Prepare release 0.5.0
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#276 Update traefik version
  go.mod
  go.sum
  helm/chart/maesh/values.yaml
  internal/providers/base/base.go
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/traefik, kind/enhancement, status/3-needs-merge

#279 Prepare release v0.6.0
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#287 Fix panic when deeting a ns
  internal/providers/kubernetes/provider.go
Labels: kind/bug/fix, provider/kubernetes, status/3-needs-merge

#288 Deploy configuration to mesh pods even if config hasn't changed
  internal/controller/controller.go
  internal/controller/handler.go
  internal/k8s/constants.go
Labels: area/configuration, kind/bug/fix, status/3-needs-merge

#282 Reduce Gocyclo to 15
  .golangci.toml
  internal/providers/smi/provider.go
Labels: area/infrastructure, area/smi, kind/enhancement, provider/smi, status/3-needs-merge

#280 Remove deprecated extensions/v1beta1 API group
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
  helm/chart/maesh/charts/tracing/templates/jaeger-deployment.yaml
  integration/resources/coredns/coredns.yaml
  integration/resources/tools/deployment.yaml
  integration/resources/whoami/whoami.yaml
Labels: area/helm, kind/enhancement

#301 Upgrade golangci-lint and fix helm version
  Dockerfile
  Makefile
  integration/integration_test.go
  integration/resources/whoami/whoami.yaml
Labels: area/helm, area/infrastructure, kind/bug/fix, status/3-needs-merge

#299 Deploy to unready nodes
  internal/controller/controller.go
Labels: area/configuration, kind/bug/fix, kind/enhancement, priority/P1, status/3-needs-merge

#302 Upgrade helm to version 2.15.1
  Makefile
  integration/integration_test.go
Labels: area/helm, kind/enhancement, status/3-needs-merge

#291 Add tag from values, default to v2.0
  helm/chart/maesh/templates/_helpers.tpl
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
  integration/integration_test.go
  integration/resources/values.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#283 make cluster domain configurable
  cmd/configuration.go
  cmd/prepare/prepare.go
  docs/content/install.md
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
  internal/k8s/client.go
Labels: area/helm, kind/enhancement, status/3-needs-merge

#304 Prepare Release 0.7.0
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#309 fix: linter timeout.
  .golangci.toml
Labels: area/infrastructure, kind/bug/fix, status/3-needs-merge

#310 add spec.selector field to Helm chart dependencies
  helm/chart/maesh/charts/metrics/templates/grafana.yaml
  helm/chart/maesh/charts/metrics/templates/prometheus.yaml
  helm/chart/maesh/charts/tracing/templates/jaeger-deployment.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#312 Remove local-test-integration
  .semaphoreci/job2.sh
  Makefile
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#315 Move liveness to dedicated entrypoint
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
Labels: area/helm, area/traefik, kind/bug/fix, status/3-needs-merge

#313 Refactor ignorewrapper
  internal/controller/controller.go
  internal/controller/handler.go
  internal/k8s/ignore.go
  internal/k8s/ignore_test.go
  internal/k8s/namespace.go
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/configuration, kind/enhancement, status/3-needs-merge

#317 Pin k3s version
  .semaphoreci/job2.sh
  Makefile
  integration/integration_test.go
Labels: area/infrastructure, kind/enhancement

#326 Re-add ignored namespace
  internal/controller/controller.go
Labels: area/controller, kind/bug/fix, status/3-needs-merge
