Repository traefik/mesh, pull requests merged in 2020-01, with the labels that each got.

#393 Add a note about helm v2
  README.md
  docs/content/install.md
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#390 Add Configuration to use HTTPS as scheme
  docs/content/configuration.md
  internal/k8s/constants.go
  internal/providers/base/base.go
  internal/providers/base/base_test.go
Labels: area/configuration, area/controller, kind/enhancement, status/3-needs-merge

#375 Use Listers instead of API Queries
  Makefile
  go.mod
  go.sum
  helm/chart/maesh/crds/smi-spec.yaml
  helm/chart/maesh/crds/smi-trafficsplits.yaml
  helm/chart/maesh/templates/controller/controller-rbac.yaml
  integration/smi_test.go
  internal/controller/api.go
  internal/controller/controller.go
  internal/k8s/client.go
  internal/k8s/client_mock.go
  internal/k8s/constants.go
  internal/providers/base/base.go
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
  internal/providers/smi/fixtures/build_configuration_http_service.yaml
  internal/providers/smi/fixtures/mock.yaml
  internal/providers/smi/fixtures/mock_tcp.yaml
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/kubernetes-client, kind/enhancement, provider/kubernetes, provider/smi, status/3-needs-merge

#398 Rework test condition
  internal/providers/smi/provider_test.go
Labels: area/smi, kind/bug/fix, status/3-needs-merge

#396 Add Versioned docs
  .travis.yml
Labels: area/documentation, area/infrastructure, kind/enhancement, status/3-needs-merge

#406 Copy CNAME File to get docs working again
  .travis.yml
Labels: area/infrastructure, status/3-needs-merge

#407 Prepare release v1.1.0-rc1
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#408 Fix chart directory
  .travis.yml
Labels: kind/bug/fix, status/3-needs-merge

#411 Document release process & steps
  CONTRIBUTING.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge
