Repository traefik/mesh, pull requests merged in 2020-11, with the labels that each got.

#774 Allow CoreDNS version strings to contain sufixes
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/dns/testdata/checkdnsprovider_supported_version_suffix.yaml
Labels: area/coredns, kind/bug/fix, status/3-needs-merge

#775 Docker authentication
  .golangci.toml
  .semaphore/semaphore.yml
  Dockerfile
  cmd/mesh/mesh.go
  integration/k3d/k3d.go
  integration/try/condition.go
  integration/try/try.go
  pkg/annotations/annotations_test.go
  pkg/annotations/middleware.go
  pkg/k8s/client.go
  pkg/provider/provider.go
  pkg/topology/builder.go
Labels: kind/enhancement, status/3-needs-merge

#780 Fix ACL example
  docs/content/examples.md
Labels: area/documentation, area/smi, kind/bug/fix, status/3-needs-merge
