Repository traefik/mesh, pull requests merged in 2020-03, with the labels that each got.

#449 Fix CI for gh-pages branch
  .semaphore/semaphore.yml
  .travis.yml
Labels: area/infrastructure, area/tests, kind/bug/fix, status/3-needs-merge

#445 Move to client interfaces, and create fixture tests for API and Controller
  go.mod
  go.sum
  integration/smi_test.go
  integration/try/try.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/fixtures/getmeshnodeconfiguration_empty.yaml
  pkg/api/fixtures/getmeshnodeconfiguration_simple.yaml
  pkg/api/fixtures/getmeshnodes_empty.yaml
  pkg/api/fixtures/getmeshnodes_one_mesh_pod.yaml
  pkg/api/fixtures/getmeshnodes_one_nonready_mesh_pod.yaml
  pkg/controller/api_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fixtures/getmeshnodeconfiguration_empty.yaml
  pkg/controller/fixtures/getmeshnodeconfiguration_simple.yaml
  pkg/controller/fixtures/getmeshnodes_empty.yaml
  pkg/controller/fixtures/getmeshnodes_one_mesh_pod.yaml
  pkg/controller/fixtures/getmeshnodes_one_nonready_mesh_pod.yaml
  pkg/controller/fixtures/mock.yaml
  pkg/deploylog/log.go
  pkg/deploylog/log_test.go
  pkg/k8s/client.go
  pkg/k8s/client_mock.go
  pkg/k8s/constants.go
  pkg/providers/kubernetes/provider.go
  pkg/providers/smi/provider.go
Labels: area/api, area/controller, area/kubernetes-client, area/tests, kind/enhancement, status/3-needs-merge

#452 Cleanup TCPPortMapping when updating/deleting a shadow service
  pkg/controller/controller.go
  pkg/controller/handler.go
  pkg/controller/service.go
  pkg/controller/service_test.go
  pkg/k8s/tcpportmapping.go
  pkg/k8s/tcpportmapping_test.go
Labels: area/controller, area/infrastructure, kind/enhancement, status/3-needs-merge

#453 Add missing Dir
  .travis.yml
Labels: area/infrastructure, area/tests, kind/bug/fix, status/3-needs-merge

#451 Allow for TargetPorts
  internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports.yaml
  internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture.yaml
  internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture_tcp.yaml
  internal/providers/kubernetes/fixtures/build_configuration_multiple_targetports_tcp.yaml
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
Labels: area/configuration, area/tests, kind/bug/fix, provider/kubernetes, status/3-needs-merge

#455 Update traefik version to v2.1.6
  go.mod
  go.sum
  integration/integration_test.go
  integration/try/try.go
  pkg/controller/controller.go
  pkg/k8s/client.go
Labels: kind/enhancement, status/3-needs-merge

#456 Prepare Release v1.1
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#459 ignore non-go 1.14 code
  .goreleaser.yml
Labels: area/infrastructure, kind/bug/fix, status/3-needs-merge

#458 Mergeback v1.1.0
  .goreleaser.yml
  helm/chart/maesh/Chart.yaml
  pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports.yaml
  pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture.yaml
  pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports_mixture_tcp.yaml
  pkg/providers/kubernetes/fixtures/build_configuration_multiple_targetports_tcp.yaml
  pkg/providers/kubernetes/provider.go
  pkg/providers/kubernetes/provider_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#454 Move prepare code to its own package
  cmd/maesh/maesh.go
  cmd/prepare/prepare.go
  integration/integration_test.go
  integration/smi_test.go
  integration/try/try.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/prepare/prepare.go
Labels: area/controller, area/infrastructure, area/kubernetes-client, kind/enhancement, status/3-needs-merge

#465 Use logrus.FieldLogger for logging
  cmd/maesh/maesh.go
  cmd/prepare/prepare.go
  integration/try/try.go
  pkg/controller/controller.go
  pkg/k8s/client.go
  pkg/prepare/prepare.go
Labels: area/logs, kind/enhancement, status/3-needs-merge

#467 Remove Helm v2 references
  README.md
  docs/content/install.md
Labels: area/documentation, area/helm, kind/enhancement, status/3-needs-merge

#462 Refactor `prepare` package for external use
  cmd/maesh/maesh.go
  cmd/prepare/prepare.go
  pkg/prepare/fixtures/checkdnsprovider_kubedns.yaml
  pkg/prepare/fixtures/checkdnsprovider_no_provider.yaml
  pkg/prepare/fixtures/checkdnsprovider_supported_version.yaml
  pkg/prepare/fixtures/checkdnsprovider_unsupported_version.yaml
  pkg/prepare/fixtures/configurecoredns_already_patched.yaml
  pkg/prepare/fixtures/configurecoredns_missing_configmap.yaml
  pkg/prepare/fixtures/configurecoredns_missing_deployment.yaml
  pkg/prepare/fixtures/configurecoredns_not_patched.yaml
  pkg/prepare/fixtures/configurekubedns_already_patched.yaml
  pkg/prepare/fixtures/configurekubedns_missing_deployment.yaml
  pkg/prepare/fixtures/configurekubedns_not_patched.yaml
  pkg/prepare/prepare.go
  pkg/prepare/prepare_test.go
Labels: area/coredns, kind/enhancement, priority/P1, status/3-needs-merge

#466 Implement the rest of the logger interfaces
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/handler.go
  pkg/controller/service.go
  pkg/controller/service_test.go
  pkg/deploylog/log.go
  pkg/deploylog/log_test.go
  pkg/providers/kubernetes/provider.go
  pkg/providers/kubernetes/provider_test.go
  pkg/providers/smi/provider.go
  pkg/providers/smi/provider_test.go
Labels: area/logs, kind/enhancement, status/3-needs-merge

#468 Fix port-mapping cleanup for HTTP services
  pkg/controller/service.go
Labels: area/controller, kind/enhancement, status/3-needs-merge

#472 Update to Go 1.14
  .semaphore/semaphore.yml
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#469 add source build note
  docs/content/install.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#470 Remove unneeded translate error method
  integration/integration_test.go
  integration/try/try.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
Labels: area/kubernetes-client, area/tests, kind/enhancement, status/3-needs-merge

#474 Update Travis to build on Go 1.14
  .travis.yml
Labels: area/infrastructure, area/tests, kind/enhancement, status/3-needs-merge
