Repository traefik/mesh, pull requests merged in 2020-04, with the labels that each got.

#480 Upgrade traefik and deps to 2.2.0
  Dockerfile
  docs/content/configuration.md
  go.mod
  go.sum
  helm/chart/maesh/templates/_helpers.tpl
  helm/chart/maesh/values.yaml
  integration/helm_test.go
  integration/integration_test.go
  integration/kubedns_test.go
  integration/kubernetes_test.go
  integration/resources/smi/access-control.json
  integration/resources/smi/traffic-split.json
  integration/resources/values.yaml
  integration/smi_test.go
  integration/try/try.go
  pkg/controller/controller.go
  pkg/controller/service.go
  pkg/controller/service_test.go
  pkg/k8s/client.go
  pkg/k8s/client_mock.go
  pkg/k8s/tcpportmapping.go
  pkg/k8s/tcpportmapping_test.go
  pkg/prepare/prepare.go
  pkg/prepare/prepare_test.go
  pkg/providers/base/base.go
  pkg/providers/smi/provider.go
  pkg/providers/smi/provider_test.go
  tmpl.Dockerfile
Labels: area/infrastructure, area/tests, kind/enhancement, status/3-needs-merge

#483 Fix typos
  CONTRIBUTING.md
  README.md
  helm/chart/README.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#484 Fix non working pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/infrastructure, kind/bug/fix, status/3-needs-merge

#485 Add service topology key logic
  pkg/controller/service.go
Labels: area/infrastructure, area/kubernetes-client, kind/enhancement, status/3-needs-merge

#488 Fix documentation typos
  docs/content/api.md
  docs/content/configuration.md
  docs/content/examples.md
  docs/content/index.md
  docs/content/install.md
  docs/content/quickstart.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#486 Remove old dependencies
  go.mod
  go.sum
  integration/integration_test.go
  integration/smi_test.go
  integration/try/try.go
  pkg/controller/service.go
  pkg/controller/service_test.go
  pkg/k8s/tcpportmapping.go
  pkg/k8s/tcpportmapping_test.go
  pkg/prepare/prepare.go
  pkg/prepare/prepare_test.go
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#491 Add semaphore build cache
  .semaphore/semaphore.yml
Labels: area/infrastructure, area/tests, kind/enhancement, status/3-needs-merge

#497 Add a contributing section to the documentation
  docs/.markdownlint.json
  docs/content/building.md
  docs/content/contributing/building-testing.md
  docs/content/contributing/documentation.md
  docs/content/contributing/maintainers.md
  docs/content/contributing/submitting-issues.md
  docs/content/contributing/submitting-pull-requests.md
  docs/content/contributing/thank-you.md
  docs/content/install.md
  docs/mkdocs.yml
  docs/scripts/verify.sh
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#504 Use semaphore build cache when running ACL integration test suites
  .semaphore/semaphore.yml
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#510 Fix discrepancy in prepare interface
  pkg/prepare/prepare.go
Labels: area/coredns, kind/bug/fix, status/3-needs-merge

#507 Fix panic when pod IP is not yet assigned
  pkg/provider/provider.go
  pkg/topology/builder.go
Labels: area/controller, kind/bug/fix, provider/kubernetes, provider/smi, status/2-needs-review

#508 Fix broken edit link in the documentation
  docs/mkdocs.yml
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#495 Create Maesh Proxy command
  .goreleaser.yml
  Makefile
  cmd/maesh/maesh.go
  cmd/proxy/proxy.go
  cmd/version/version.go
  docs/content/configuration.md
  docs/content/install.md
  go.mod
  go.sum
  helm/chart/maesh/templates/_helpers.tpl
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
  helm/chart/maesh/values.yaml
  integration/acl_disabled_test.go
  integration/acl_enabled_test.go
  integration/helm_test.go
  integration/integration_test.go
  integration/kubedns_test.go
  integration/resources/values.yaml
  pkg/version/version.go
Labels: area/traefik, kind/enhancement, status/3-needs-merge

#521 Disable mesh proxy dashboard in Helm chart
  helm/chart/maesh/templates/mesh/mesh-daemonset.yaml
Labels: area/api, area/traefik, kind/bug/fix, status/3-needs-merge

#527 Remove dependency from provider to topology builder
  pkg/controller/controller.go
  pkg/provider/provider.go
  pkg/provider/provider_test.go
Labels: kind/enhancement, priority/P1, provider, status/3-needs-merge

#530 Add Go report card badge to readme
  README.md
Labels: area/documentation, kind/task, status/3-needs-merge

#528 Remove deprecated SMI option in the Helm chart
  docs/content/install.md
  docs/content/migration/helm-chart.md
  docs/content/migration/maesh-v1.md
  docs/mkdocs.yml
  docs/scripts/verify.sh
  helm/chart/maesh/Guidelines.md
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/values.yaml
  integration/acl_enabled_test.go
  integration/helm_test.go
  integration/integration_test.go
  integration/kubedns_test.go
  integration/resources/values.yaml
Labels: area/documentation, area/helm, status/3-needs-merge
