Repository traefik/mesh, pull requests merged in 2020-09, with the labels that each got.

#719 Update go to v1.15
  .semaphore/semaphore.yml
  .travis.yml
  Dockerfile
  docs/content/contributing/building-testing.md
  go.mod
  go.sum
  tmpl.Dockerfile
Labels: area/infrastructure, area/traefik, kind/enhancement, status/3-needs-merge

#721 Update apiVersion of RBAC resources in Helm
  docs/content/compatibility.md
  helm/chart/maesh/templates/controller/controller-rbac.yaml
  helm/chart/maesh/templates/coredns/coredns-rbac.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#722 Upgrade golangci-lint version to v1.30
  .golangci.toml
  Dockerfile
  integration/k3d/k3d.go
  pkg/api/api_test.go
  pkg/controller/controller.go
  pkg/dns/dns_test.go
  pkg/k8s/client_mock.go
  pkg/topology/builder_test.go
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#726 Add app and release selector to the controller service
  helm/chart/maesh/templates/controller/controller-service.yaml
  helm/chart/maesh/templates/coredns/coredns-deployment.yaml
  helm/chart/maesh/templates/coredns/coredns-service.yaml
  helm/chart/maesh/templates/mesh/mesh-service.yaml
Labels: area/controller, area/helm, kind/bug/fix, status/3-needs-merge

#727 Remove unnecessary pod affinity config in controller resource
  docs/content/install.md
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  helm/chart/maesh/templates/controller/controller-sa.yaml
  helm/chart/maesh/templates/mesh/mesh-pdb.yaml
  helm/chart/maesh/templates/mesh/mesh-service.yaml
Labels: area/helm, kind/enhancement, status/3-needs-merge

#732 Add version tag to whoami images
  docs/content/examples.md
  docs/content/quickstart.md
  integration/acl_disabled_test.go
  integration/acl_enabled_test.go
  integration/coredns_test.go
  integration/kubedns_test.go
  integration/testdata/acl_disabled/http/1.server.yaml
  integration/testdata/acl_disabled/tcp/1.server.yaml
  integration/testdata/acl_disabled/traffic-split/2.server-v1.yaml
  integration/testdata/acl_disabled/traffic-split/3.server-v2.yaml
  integration/testdata/acl_disabled/udp/1.server.yaml
  integration/testdata/acl_enabled/http/1.server.yaml
  integration/testdata/acl_enabled/http/3.server-api.yaml
  integration/testdata/acl_enabled/http/4.server-header.yaml
  integration/testdata/acl_enabled/traffic-split/1.server-split.yaml
Labels: area/documentation, area/tests, kind/enhancement, status/3-needs-merge

#733 Upgrade golangci-lint version to v1.31
  .golangci.toml
  Dockerfile
  pkg/dns/dns.go
  pkg/topology/builder.go
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#734 Fix CNAME for documentation
  docs/CNAME
Labels: area/documentation, bot/light-review, kind/bug/fix, status/3-needs-merge

#735 Prepare v1.4.0-rc1
  helm/chart/mesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#736 Remove Helm chart
  .semaphore/semaphore.yml
  .travis.yml
  Makefile
  README.md
  docs/content/contributing/building-testing.md
  docs/content/install.md
  docs/content/migration/helm-chart.md
  docs/content/quickstart.md
  helm/chart/mesh/.helmignore
  helm/chart/mesh/Chart.yaml
  helm/chart/mesh/Guidelines.md
  helm/chart/mesh/README.md
  helm/chart/mesh/charts/metrics/Chart.yaml
  helm/chart/mesh/charts/metrics/dashboards/traefik.json
  helm/chart/mesh/charts/metrics/templates/grafana-pdb.yaml
  helm/chart/mesh/charts/metrics/templates/grafana.yaml
  helm/chart/mesh/charts/metrics/templates/prometheus-pdb.yaml
  helm/chart/mesh/charts/metrics/templates/prometheus.yaml
  helm/chart/mesh/charts/metrics/templates/rbac.yaml
  helm/chart/mesh/charts/metrics/templates/storage.yaml
  helm/chart/mesh/charts/metrics/values.yaml
  helm/chart/mesh/charts/tracing/Chart.yaml
  helm/chart/mesh/charts/tracing/templates/jaeger-deployment.yaml
  helm/chart/mesh/charts/tracing/templates/jaeger-pdb.yaml
  helm/chart/mesh/charts/tracing/templates/jaeger-sa.yaml
  helm/chart/mesh/charts/tracing/templates/jaeger-services.yaml
  helm/chart/mesh/charts/tracing/values.yaml
  helm/chart/mesh/templates/NOTES.txt
  helm/chart/mesh/templates/_helpers.tpl
  helm/chart/mesh/templates/controller/controller-deployment.yaml
  helm/chart/mesh/templates/controller/controller-pdb.yaml
  helm/chart/mesh/templates/controller/controller-rbac.yaml
  helm/chart/mesh/templates/controller/controller-sa.yaml
  helm/chart/mesh/templates/controller/controller-service.yaml
  helm/chart/mesh/templates/controller/hooks/cleanup-hook.yaml
  helm/chart/mesh/templates/coredns/coredns-configmap.yaml
  helm/chart/mesh/templates/coredns/coredns-deployment.yaml
  helm/chart/mesh/templates/coredns/coredns-rbac.yaml
  helm/chart/mesh/templates/coredns/coredns-sa.yaml
  helm/chart/mesh/templates/coredns/coredns-service.yaml
  helm/chart/mesh/templates/proxy/proxy-daemonset.yaml
  helm/chart/mesh/templates/proxy/proxy-sa.yaml
  helm/chart/mesh/values.yaml
  integration/helm_test.go
  integration/integration_test.go
  integration/testdata/crds/smi-access.yaml
  integration/testdata/crds/smi-specs.yaml
  integration/testdata/crds/smi-split.yaml
Labels: area/helm, area/infrastructure, kind/bug/fix, status/3-needs-merge

#737 Apply new documentation style
  .github/ISSUE_TEMPLATE/config.yml
  .travis.yml
  CODE_OF_CONDUCT.md
  Makefile
  README.md
  docs/CNAME
  docs/content/assets/img/after-traefik-mesh-graphic.svg
  docs/content/assets/img/before-traefik-mesh-graphic.svg
  docs/content/assets/img/traefik-mesh-logo.svg
  docs/content/assets/img/traefik-mesh.logo.horizontal.png
  docs/content/assets/img/traefik-mesh.png
  docs/content/assets/styles/header.css
  docs/content/assets/styles/product-switcher.css
  docs/content/configuration.md
  docs/content/contributing/documentation.md
  docs/content/contributing/submitting-issues.md
  docs/content/index.md
  docs/mkdocs.yml
  docs/scripts/verify.sh
  docs/theme/assets/images/traefik-enterprise-logo.svg
  docs/theme/assets/images/traefik-labs.svg
  docs/theme/assets/images/traefik-mesh-horizontal-logo-color.svg
  docs/theme/assets/images/traefik-mesh-logo.svg
  docs/theme/assets/images/traefik-pilot-logo.svg
  docs/theme/assets/images/traefik-proxy-logo.svg
  docs/theme/main.html
  docs/theme/partials/company-header.html
  docs/theme/partials/product-switcher.html
Labels: area/documentation, area/infrastructure, bot/light-review, kind/bug/fix, status/3-needs-merge

#738 Fix documentation deployment
  .travis.yml
Labels: area/documentation, area/infrastructure, bot/light-review, kind/bug/fix, status/3-needs-merge

#739 Upgrade Traefik dependency version to v2.3.0
  go.mod
  go.sum
Labels: area/infrastructure, area/traefik, bot/light-review, kind/bug/fix, status/3-needs-merge

#744 Bump go module version to v2
  .goreleaser.yml
  Makefile
  cmd/cleanup/cleanup.go
  cmd/mesh/mesh.go
  cmd/prepare/prepare.go
  cmd/version/version.go
  docs/content/contributing/building-testing.md
  go.mod
  integration/acl_disabled_test.go
  integration/acl_enabled_test.go
  integration/coredns_test.go
  integration/k3d/k3d.go
  integration/kubedns_test.go
  integration/tool/tool.go
  integration/try/try.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/portmapping_test.go
  pkg/controller/service.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/provider/key.go
  pkg/provider/provider.go
  pkg/provider/provider_test.go
  pkg/provider/rule.go
  pkg/topology/builder.go
  pkg/topology/builder_test.go
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#743 Remove maesh domain support
  integration/acl_disabled_test.go
  integration/coredns_test.go
  integration/kubedns_test.go
  integration/testdata/kubedns/coredns.yaml
  integration/testdata/traefik-mesh/controller-acl-disabled.yaml
  integration/testdata/traefik-mesh/controller-acl-enabled.yaml
  integration/testdata/traefik-mesh/proxy.yaml
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/dns/testdata/configurecoredns_17_already_patched.yaml
  pkg/dns/testdata/configurecoredns_17_custom_already_patched.yaml
  pkg/dns/testdata/configurecoredns_already_patched.yaml
  pkg/dns/testdata/configurecoredns_custom_already_patched.yaml
  pkg/dns/testdata/restorecoredns_custom_not_patched.yaml
  pkg/dns/testdata/restorecoredns_custom_patched.yaml
  pkg/dns/testdata/restorecoredns_patched.yaml
  pkg/dns/testdata/restorekubedns_already_patched.yaml
  pkg/provider/rule.go
  pkg/provider/testdata/acl-disabled-http-basic-config.json
  pkg/provider/testdata/acl-disabled-http-traffic-split-config.json
  pkg/provider/testdata/acl-enabled-http-basic-config.json
  pkg/provider/testdata/acl-enabled-http-route-group-config.json
  pkg/provider/testdata/acl-enabled-http-traffic-split-config.json
  pkg/provider/testdata/acl-enabled-http-traffic-split-http-route-group-config.json
  pkg/provider/testdata/annotations-scheme-config.json
Labels: area/kubedns, area/provider, kind/enhancement, status/3-needs-merge

#742 Remove support of maesh env and config files
  cmd/loaders.go
Labels: area/configuration, kind/enhancement, status/3-needs-merge

#741 Remove maesh annotation support
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
Labels: area/configuration, area/controller, kind/enhancement, status/3-needs-merge

#745 Remove smi flag
  cmd/configuration.go
  cmd/mesh/mesh.go
  cmd/prepare/prepare.go
  pkg/controller/controller_test.go
Labels: area/controller, area/helm, area/prepare, status/3-needs-merge

#754 Remove deprecated debug flag
  cmd/cleanup/cleanup.go
  cmd/configuration.go
  cmd/log.go
  cmd/mesh/mesh.go
  cmd/prepare/prepare.go
Labels: area/logs, kind/enhancement, status/3-needs-merge
