Repository traefik/mesh, pull requests merged in 2020-02, with the labels that each got.

#400 Rework Integration tests
  .golangci.toml
  .semaphoreci/golang.sh
  .semaphoreci/setup.sh
  Dockerfile
  Makefile
  go.mod
  go.sum
  integration/coredns_test.go
  integration/helm_test.go
  integration/integration_test.go
  integration/kubedns_test.go
  integration/kubernetes_test.go
  integration/resources/kubernetes/config.json
  integration/resources/smi/access-control.json
  integration/resources/smi/access-control/1.sas.yaml
  integration/resources/smi/access-control/2.pods.yaml
  integration/resources/smi/access-control/3.services.yaml
  integration/resources/smi/access-control/4.hrgs.yaml
  integration/resources/smi/access-control/5.trs.yaml
  integration/resources/smi/access-control/6.tts.yaml
  integration/resources/smi/crds/smi-access.yaml
  integration/resources/smi/crds/smi-spec.yaml
  integration/resources/smi/crds/smi-trafficsplits.yaml
  integration/resources/smi/traffic-split.json
  integration/resources/smi/traffic-split/1.sas.yaml
  integration/resources/smi/traffic-split/2.pods.yaml
  integration/resources/smi/traffic-split/3.services.yaml
  integration/resources/smi/traffic-split/4.hrgs.yaml
  integration/resources/smi/traffic-split/5.tts.yaml
  integration/resources/smi/traffic-split/6.tspls.yaml
  integration/resources/tools/deployment.yaml
  integration/smi_test.go
  integration/try/condition.go
  integration/try/try.go
Labels: area/controller, area/infrastructure, area/tests, kind/enhancement, status/3-needs-merge

#420 Add informer sync test to prepare command
  cmd/configuration.go
  cmd/prepare/prepare.go
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  integration/integration_test.go
  integration/resources/smi/access-control-broken/1.tts.yaml
  integration/smi_test.go
  internal/k8s/client.go
Labels: area/controller, area/smi, kind/bug/fix, status/3-needs-merge

#419 Update regex rule for HTTPRouteGroup
  integration/smi_test.go
  internal/providers/smi/provider.go
  internal/providers/smi/provider_test.go
Labels: area/configuration, area/smi, kind/bug/fix, status/3-needs-merge

#421 Allow single test suites to be run
  Makefile
  docs/content/building.md
Labels: area/infrastructure, area/tests, kind/enhancement, status/3-needs-merge

#422 Setup semaphore v2
  .semaphore/semaphore.yml
  Makefile
Labels: area/infrastructure, area/tests, kind/enhancement, status/3-needs-merge

#429 Setup semaphoreci v2
  .semaphore/semaphore.yml
  .semaphoreci/golang.sh
  .semaphoreci/job1.sh
  .semaphoreci/job2.sh
  .semaphoreci/setup.sh
  .semaphoreci/vars
  Makefile
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#431 Add a note about being a namespaced ressource
  docs/content/configuration.md
Labels: area/documentation, area/smi, kind/enhancement, status/3-needs-merge

#430 Enhance logging to show expects for TCPRoute and HTTPRoute
  internal/providers/smi/provider.go
Labels: area/logs, area/smi, kind/enhancement, status/3-needs-merge

#432 Provide an SMI example
  docs/content/examples.md
Labels: area/documentation, area/smi, kind/enhancement, status/3-needs-merge

#428 Ensure only correct port endpoints get added to proxy service
  internal/providers/kubernetes/fixtures/build_configuration_multiple_ports.yaml
  internal/providers/kubernetes/fixtures/build_configuration_multiple_ports_tcp.yaml
  internal/providers/kubernetes/provider.go
  internal/providers/kubernetes/provider_test.go
Labels: area/configuration, kind/bug/fix, provider/kubernetes, status/3-needs-merge

#435 Prepare release v1.1.0-rc2
  helm/chart/maesh/Chart.yaml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#436 Wait fort the k3s cluster to come up before running tests
  integration/integration_test.go
Labels: area/infrastructure, area/tests, kind/bug/fix, status/3-needs-merge

#437 Move `/internal` packages into `/pkg`
  cmd/maesh/maesh.go
  cmd/prepare/prepare.go
  integration/integration_test.go
  integration/try/try.go
  pkg/controller/api.go
  pkg/controller/api_test.go
  pkg/controller/controller.go
  pkg/controller/handler.go
  pkg/controller/log.go
  pkg/controller/log_test.go
  pkg/k8s/client.go
  pkg/k8s/client_mock.go
  pkg/k8s/client_test.go
  pkg/k8s/constants.go
  pkg/k8s/fixtures/mock.yaml
  pkg/k8s/ignore.go
  pkg/k8s/ignore_test.go
  pkg/k8s/namespace.go
  pkg/k8s/namespace_test.go
  pkg/k8s/service.go
  pkg/k8s/service_test.go
  pkg/providers/base/base.go
  pkg/providers/base/base_test.go
  pkg/providers/kubernetes/fixtures/build_configuration_simple.yaml
  pkg/providers/kubernetes/fixtures/build_configuration_simple_http_middlewares.yaml
  pkg/providers/kubernetes/fixtures/build_configuration_simple_tcp.yaml
  pkg/providers/kubernetes/fixtures/build_service_missing_endpoints.yaml
  pkg/providers/kubernetes/fixtures/build_service_simple.yaml
  pkg/providers/kubernetes/provider.go
  pkg/providers/kubernetes/provider_test.go
  pkg/providers/smi/fixtures/build_configuration_http_service.yaml
  pkg/providers/smi/fixtures/mock.yaml
  pkg/providers/smi/fixtures/mock_tcp.yaml
  pkg/providers/smi/provider.go
  pkg/providers/smi/provider_test.go
  pkg/signals/signal.go
  pkg/signals/signal_posix.go
  pkg/signals/signal_windows.go
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#424 Update SemaphoreCI Badge
  README.md
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#410 Update k3s to use k8s 1.17
  Makefile
Labels: area/infrastructure, kind/enhancement, status/3-needs-merge

#438 Mergeback v1.1 rc2
  .semaphoreci/golang.sh
  .semaphoreci/job1.sh
  .semaphoreci/job2.sh
  .semaphoreci/setup.sh
  .semaphoreci/vars
  docs/content/configuration.md
  docs/content/examples.md
  helm/chart/maesh/Chart.yaml
  integration/resources/smi/access-control.json
  integration/resources/smi/traffic-split.json
  pkg/providers/kubernetes/fixtures/build_configuration_multiple_ports.yaml
  pkg/providers/kubernetes/fixtures/build_configuration_multiple_ports_tcp.yaml
  pkg/providers/kubernetes/provider.go
  pkg/providers/kubernetes/provider_test.go
  pkg/providers/smi/provider.go
  pkg/providers/smi/provider_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#439 Extract TCPStateTable logic from the controller
  .golangci.toml
  cmd/configuration.go
  cmd/maesh/maesh.go
  helm/chart/maesh/templates/controller/controller-deployment.yaml
  integration/coredns_test.go
  integration/kubernetes_test.go
  integration/resources/tcp-state-table/configmap.yaml
  integration/smi_test.go
  pkg/controller/api.go
  pkg/controller/controller.go
  pkg/controller/handler.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/tcpportmapping.go
  pkg/k8s/tcpportmapping_test.go
  pkg/providers/kubernetes/provider.go
  pkg/providers/kubernetes/provider_test.go
  pkg/providers/smi/provider.go
  pkg/providers/smi/provider_test.go
Labels: area/controller, kind/enhancement, status/3-needs-merge

#441 Wait for Pod IPs to be assigned in Integration test
  integration/smi_test.go
  integration/try/try.go
Labels: area/infrastructure, area/tests, kind/bug/fix, kind/enhancement, status/3-needs-merge

#444 Add bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: area/documentation, area/infrastructure, kind/enhancement, status/3-needs-merge

#440 Add host to API bind
  cmd/configuration.go
  cmd/maesh/maesh.go
  integration/integration_test.go
  pkg/controller/api.go
  pkg/controller/api_test.go
  pkg/controller/controller.go
Labels: area/api, kind/enhancement, status/3-needs-merge

#446 Shadow service manager
  pkg/controller/controller.go
  pkg/controller/handler.go
  pkg/controller/service.go
  pkg/controller/service_test.go
  pkg/k8s/client.go
  pkg/providers/base/base.go
  pkg/providers/kubernetes/provider.go
  pkg/providers/smi/provider.go
Labels: area/controller, area/kubernetes-client, kind/enhancement, status/3-needs-merge
