Repository traefik/mesh, pull requests merged in 2021-01, with the labels that each got.

#772 Add DNS resolver and server
  .gitignore
  cmd/cleanup/config.go
  cmd/dns/config.go
  cmd/dns/dns.go
  cmd/mesh/config.go
  cmd/mesh/mesh.go
  cmd/prepare/config.go
  cmd/prepare/prepare.go
  docs/content/install.md
  go.mod
  go.sum
  integration/acl_disabled_test.go
  integration/acl_enabled_test.go
  integration/coredns_test.go
  integration/integration_test.go
  integration/kubedns_test.go
  integration/testdata/dns/kubedns.yaml
  integration/testdata/dns/whoami-shadow-service.yaml
  integration/testdata/kubedns/coredns.yaml
  integration/testdata/traefik-mesh/controller-acl-disabled.yaml
  integration/testdata/traefik-mesh/controller-acl-enabled.yaml
  integration/testdata/traefik-mesh/dns.yaml
  integration/testdata/traefik-mesh/values.yaml
  pkg/controller/service.go
  pkg/controller/service_test.go
  pkg/dns/client.go
  pkg/dns/client_test.go
  pkg/dns/resolver.go
  pkg/dns/resolver_test.go
  pkg/dns/server.go
  pkg/dns/server_test.go
  pkg/dns/testdata/configurecoredns_17_custom_already_patched.yaml
  pkg/dns/testdata/configurecoredns_1_3.yaml
  pkg/dns/testdata/configurecoredns_1_4_already_patched.yaml
  pkg/dns/testdata/configurecoredns_already_patched.yaml
  pkg/dns/testdata/configurecoredns_custom_already_patched.yaml
  pkg/dns/testdata/configurecoredns_custom_not_patched.yaml
  pkg/dns/testdata/configurecoredns_missing_configmap.yaml
  pkg/dns/testdata/configurecoredns_not_patched.yaml
  pkg/dns/testdata/configurekubedns_already_patched.yaml
  pkg/dns/testdata/configurekubedns_not_patched.yaml
  pkg/dns/testdata/configurekubedns_optional_configmap.yaml
  pkg/dns/testdata/restorecoredns_custom_not_patched.yaml
  pkg/dns/testdata/restorecoredns_custom_patched.yaml
  pkg/dns/testdata/restorecoredns_not_patched.yaml
  pkg/dns/testdata/restorecoredns_patched.yaml
  pkg/dns/testdata/restorekubedns_already_patched.yaml
  pkg/dns/testdata/restorekubedns_not_patched.yaml
  pkg/k8s/labels.go
Labels: area/coredns, area/kubedns, kind/enhancement, status/3-needs-merge

#782 New Traefiklabs theme
  docs/content/assets/styles/atom-one-light.css
  docs/content/assets/styles/content.css
  docs/content/assets/styles/footer.css
  docs/content/assets/styles/header.css
  docs/content/assets/styles/menu.css
  docs/content/assets/styles/product-switcher.css
  docs/content/assets/styles/root.css
  docs/docs.Dockerfile
  docs/mkdocs.yml
  docs/requirements.txt
Labels: area/documentation, area/infrastructure, kind/enhancement, status/3-needs-merge

#784 Use github Action to build and publish documentation
  .github/workflows/documentation.yml
  .travis.yml
Labels: area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#786 Remove theme folder in docs
  .github/workflows/pull_request.yml
  .travis.yml
  docs/content/configuration.md
  docs/theme/assets/images/traefik-enterprise-logo.svg
  docs/theme/assets/images/traefik-labs.svg
  docs/theme/assets/images/traefik-mesh-horizontal-logo-color.svg
  docs/theme/assets/images/traefik-mesh-logo.svg
  docs/theme/assets/images/traefik-pilot-logo.svg
  docs/theme/assets/images/traefik-proxy-logo.svg
  docs/theme/main.html
  docs/theme/partials/company-header.html
  docs/theme/partials/product-switcher.html
Labels: area/documentation, area/infrastructure, kind/bug/fix, status/3-needs-merge
