Repository traefik/mesh, pull requests merged in 2021-08, with the labels that each got.

#794 Fix html-proofer installation
  Makefile
  docs/check.Dockerfile
  integration/k3d/k3d.go
Labels: kind/bug/fix, status/3-needs-merge, area/infrastructure

#795 Update to go1.16
  .semaphore/semaphore.yml
  .travis.yml
  Dockerfile
  cmd/loaders.go
  go.mod
  go.sum
  integration/try/condition.go
  pkg/api/api.go
  pkg/controller/portmapping_test.go
  pkg/k8s/client_mock.go
  pkg/provider/provider_test.go
  pkg/topology/builder_test.go
  tmpl.Dockerfile
Labels: kind/bug/fix, status/3-needs-merge, area/infrastructure

#790 Properly detect CoreDNS version with suffixes and bump support to CoreDNS < 1.9.0
  go.mod
  go.sum
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/dns/testdata/checkdnsprovider_supported_min_version_suffix.yaml
  pkg/dns/testdata/checkdnsprovider_unsupported_version_suffix.yaml
  pkg/dns/testdata/configurecoredns_17_suffix.yaml
Labels: kind/bug/fix, status/3-needs-merge, area/coredns

#796 Release with semaphore
  .semaphore/semaphore.yml
  .travis.yml
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure

#797 ci: fix release workflow
  .semaphore/semaphore.yml
Labels: kind/bug/fix, status/3-needs-merge, area/infrastructure

#799 chore: update mkdocs dependency version
  docs/requirements.txt
Labels: kind/bug/fix, status/3-needs-merge
