Repository traefik/mesh, pull requests merged in 2022-08, with the labels that each got.

#824 Remove Maxium CoreDNS Version Requirement
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/dns/testdata/checkdnsprovider_unsupported_version_suffix.yaml
Labels: kind/bug/fix, status/3-needs-merge, area/coredns

#823 Fix CoreDNS Detection
  integration/coredns_test.go
  integration/testdata/traefik-mesh/controller-acl-disabled.yaml
  integration/testdata/traefik-mesh/controller-acl-enabled.yaml
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/dns/testdata/checkdnsprovider_coredns_using_label.yaml
Labels: kind/bug/fix, status/3-needs-merge, area/coredns

#825 Fix publish-images step of release process
  .semaphore/semaphore.yml
  Makefile
Labels: kind/bug/fix, status/3-needs-merge, area/infrastructure

#827 Update golangci-lint to v1.48.0
  .golangci.toml
  Dockerfile
  pkg/api/api.go
  pkg/provider/provider.go
Labels: bot/light-review, kind/enhancement, status/3-needs-merge, area/infrastructure

#828 Update to go1.19
  .golangci.toml
  .semaphore/semaphore.yml
  Dockerfile
  docs/content/contributing/building-testing.md
  go.mod
  go.sum
  tmpl.Dockerfile
Labels: bot/light-review, kind/enhancement, status/3-needs-merge, area/infrastructure

#829 Update Traefik dependency to v2.8.3
  .golangci.toml
  go.mod
  go.sum
  integration/acl_disabled_test.go
  integration/acl_enabled_test.go
  integration/testdata/traefik-mesh/proxy.yaml
Labels: bot/light-review, kind/bug/fix, status/3-needs-merge, area/traefik

#826 Fix CoreDNS patching on RKE environments
  integration/testdata/traefik-mesh/controller-acl-disabled.yaml
  integration/testdata/traefik-mesh/controller-acl-enabled.yaml
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/dns/testdata/checkdnsprovider_coredns_using_label.yaml
  pkg/dns/testdata/checkdnsprovider_supported_version_rke.yaml
  pkg/dns/testdata/configurecoredns_not_patched_rke.yaml
  pkg/dns/testdata/restorecoredns_patched_rke.yaml
Labels: kind/bug/fix, status/3-needs-merge

#830 Update k3d to v5.4.4
  Makefile
  integration/acl_disabled_test.go
  integration/acl_enabled_test.go
  integration/coredns_test.go
  integration/integration_test.go
  integration/k3d/k3d.go
  integration/kubedns_test.go
  integration/testdata/acl_disabled/http/1.server.yaml
  integration/testdata/acl_disabled/traffic-split/2.server-v1.yaml
  integration/testdata/acl_disabled/traffic-split/3.server-v2.yaml
  integration/testdata/acl_disabled/udp/1.server.yaml
  integration/testdata/acl_enabled/http/1.server.yaml
  integration/testdata/acl_enabled/http/3.server-api.yaml
  integration/testdata/acl_enabled/http/4.server-header.yaml
  integration/testdata/acl_enabled/traffic-split/1.server-split.yaml
  integration/testdata/crds/smi-access.yaml
  integration/testdata/crds/smi-specs.yaml
  integration/testdata/crds/smi-split.yaml
  integration/testdata/kubedns/coredns.yaml
  integration/testdata/kubedns/kubedns.yaml
  integration/testdata/traefik-mesh/controller-acl-disabled.yaml
  integration/testdata/traefik-mesh/controller-acl-enabled.yaml
  integration/testdata/traefik-mesh/proxy.yaml
  integration/tool/tool.go
Labels: bot/light-review, kind/bug/fix, status/3-needs-merge, area/infrastructure, area/tests
