Repository traefik/mesh, pull requests merged in 2022-01, with the labels that each got.

#808 Update k8s.io/client-go dependency to v0.22.5
  docs/content/compatibility.md
  go.mod
  go.sum
  pkg/controller/service.go
  pkg/controller/service_test.go
Labels: kind/bug/fix, status/3-needs-merge, area/controller, area/services

#812 Update copyright for 2022
  LICENSE
  docs/mkdocs.yml
Labels: kind/bug/fix, status/3-needs-merge, area/documentation

#810 Update to go1.17
  .golangci.toml
  .semaphore/semaphore.yml
  Dockerfile
  README.md
  cmd/cleanup/cleanup.go
  cmd/context.go
  cmd/log.go
  cmd/mesh/mesh.go
  cmd/prepare/prepare.go
  cmd/version/version.go
  docs/content/contributing/building-testing.md
  go.mod
  go.sum
  integration/coredns_test.go
  integration/testdata/traefik-mesh/proxy.yaml
  pkg/annotations/annotations_test.go
  pkg/annotations/middleware_test.go
  pkg/api/api_test.go
  pkg/cleanup/cleanup_test.go
  pkg/controller/controller_test.go
  pkg/controller/handler_test.go
  pkg/controller/portmapping_test.go
  pkg/controller/service_test.go
  pkg/dns/dns_test.go
  pkg/k8s/client_mock.go
  pkg/provider/provider_test.go
  pkg/topology/builder_test.go
  pkg/topology/topology_test.go
  tmpl.Dockerfile
Labels: kind/bug/fix, status/3-needs-merge, area/infrastructure
